spring.application.name=stats-hockey

# URL da Base de Dados (ajusta o nome 'stats_hockey' para o teu)
spring.datasource.url=jdbc:mysql://localhost:3306/stats_hoquei

# O teu utilizador e password do MySQL Workbench
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate (para o Spring criar as tabelas se não existirem)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true